# Basic
name:               "Feline Instruction Manual"
description:        "Cats are hard"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//brianshayne.github.io/cat-manual"
author:             "Donohue"
twitter:
  username:         "dianbronohue"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "//brianshayne.github.io/cat-manual"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           ""
  - name:           "Manual"
    href:           ""

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
